name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_NAME: 'FishbowlInventory.RestApi.csproj'
  PROJECT_DIR: 'source'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps: 
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_NAME }}
        working-directory: ${{ env.PROJECT_DIR }}

      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_NAME }} --no-restore --configuration Release
        working-directory: ${{ env.PROJECT_DIR }}

      - name: 'Get version'
        id: version
        uses: battila7/get-version-action@v2

      - name: 'Pack project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: 'Push package'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
